"""initial_schema

Revision ID: 12a6c88a1d94
Revises: 
Create Date: 2026-05-23 13:56:12.719218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12a6c88a1d94'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('authorized_pickups', 'relationship')
    op.alter_column('children', 'registration_number',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.drop_constraint(op.f('children_registration_number_key'), 'children', type_='unique')
    op.drop_column('emergency_contacts', 'relationship')
    op.alter_column('parent_child', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'APPROVED'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('parent_child', 'status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'APPROVED'::character varying"))
    op.add_column('emergency_contacts', sa.Column('relationship', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('children_registration_number_key'), 'children', ['registration_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('children', 'registration_number',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.add_column('authorized_pickups', sa.Column('relationship', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
